MGMT-1722 Modify 2nd ignition to create parameter file to Openshift for DHCP address allocation
oshercc/ignition-manifests-and-kubeconfig-generate pull request #21
Opened 2020-08-09 14:52 UTC by ori-amizur

2020-08-09 18:27 UTC, yevgeny-shnaidman approved these changes

2020-08-09 18:27 UTC, yevgeny-shnaidman commented on render_files.py
> +            entry = {"filesystem": "root",
Please , add a TODO note here to change it once we move to ignition 3.0

2020-08-09 18:28 UTC, yevgeny-shnaidman commented on render_files.py
> +        add_dhcp_allocation_file(ignition_file, dhcp_allocation_file)
Maybe you can also add a test ( the same way as for BMH), that will allow us testing and verifying ignition locally (on laptop)

2020-08-11 06:17 UTC, romfreiman requested changes
This is not the way to go. We should update the MCS not the first igntion

2020-08-11 06:19 UTC, romfreiman commented
Please dont merge. This is incorrect solution

2020-08-11 06:19 UTC, romfreiman requested changes
Please dont merge. this is incorrect solution

2020-08-11 06:55 UTC, eranco74 approved these changes

2020-08-11 06:57 UTC, eranco74 requested changes

2020-08-11 06:57 UTC, eranco74 commented on render_files.py
> +        add_dhcp_allocation_file(ignition_file, dhcp_allocation_file)
You need to update the master ignition not the bootstrap, no?

2022-11-16 05:04 UTC, closed without merging